Fix add resource and refactor TreeView components
MapColonies/fusion-manager pull request #2
Opened 2020-08-02 11:26 UTC by shimoncohen

Fixed:
* adding resource to the map
* now using url as unique value instead of resource name
* moved some dependencies to dev

Refactor:
* tree view components are now generic

Added:
* resource level view
* styling configurations for prettier and commitlint

2020-08-02 12:48 UTC, asafMasa requested changes

2020-08-02 12:48 UTC, asafMasa commented on .prettierrc
> +  }
enter

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Groups.js
> +    const res = await GetResource(path, name);
camelCase

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Item/Item.js
> +            // itemId={item.name}
delete comments

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Item/OpacitySlider.js
>        setOpacity(newValue);
rename CustomizedSlider to OpacitySlider

2020-08-02 12:48 UTC, asafMasa commented on src/App.js
> +import { useSelector } from "react-redux";
'

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Selector/TreeView.js
> +      // <TreeItem
remove remark

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Selector/VersionSelect.js
> +  //   const selectItem = async function (version) {
remove remarks

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Selector/VersionView.js
> +  // const selectItem = async function (version) {
remove remarks

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Selector/VersionView.js
> +          // <TreeItem
remove remarks

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Group/Selector/VersionView.js
> +        nodeId={item.latest.name + path}
check if .id should be used

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Map/Map.js
>      setVisible(!visible);
check if INITIALIZE_MAP  is needed

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Map/Map.js
> +    const res = await GetProject(path, name);
camelCase

2020-08-02 12:48 UTC, asafMasa commented on src/Components/Map/Map.js
> +    dispatch({ type: INITIALIZE_STORE, payload: res.latest.resources });
check name (INITIALIZE_STORE) validity

2020-08-02 12:48 UTC, asafMasa commented on src/Config/urls.js
> +const baseUrl = 'http://localhost:8000'; // 'https://gee.covid-97.com';
use config package

2020-08-02 12:48 UTC, asafMasa commented on src/Requests/requests.js
> +async function GetFromServer(url, path) {
camelCase

2020-08-02 12:48 UTC, asafMasa commented on src/Requests/requests.js
> +  const projects = await Axios.get(url + serachPath);
try catch and write to log

2020-08-02 12:48 UTC, asafMasa commented on src/Requests/requests.js
> +  const results = await Axios.get(rootPath + query);
try catch and write to log
change to meaningful names

2020-08-02 12:48 UTC, asafMasa commented on src/Store/Reducers/dataReducer.js
> +        const groups = draft.data["groups"];
'

2020-08-02 12:48 UTC, asafMasa commented on src/Store/Reducers/dataReducer.js
> +        draft.data.items[action.payload.id].mask.white_fill = ~~action.payload
~~?

2020-08-02 12:48 UTC, asafMasa commented on src/Util/mapDataUtil.js
> +    groups["level-" + resource.level].itemsIds.push(resource.id);
'

2020-08-02 12:48 UTC, asafMasa commented on src/Util/mapUtil.js
> +    name: 'OSM',
const

2020-08-02 12:48 UTC, asafMasa commented on src/Util/mapUtil.js
> +      parseInt(group.get('name').replace('level-', '')) >=
const groupPrefix

2020-08-02 12:48 UTC, asafMasa commented on src/Util/treeUtil.js
> +}
enter

2020-08-03 14:48 UTC, shimoncohen commented on src/Store/Reducers/dataReducer.js
> +        draft.data.items[action.payload.id].mask.white_fill = ~~action.payload
Turns boolean to an integer value.

2020-08-03 15:30 UTC, asafMasa approved these changes

2020-08-03 15:30 UTC, asafMasa commented on package.json
> +    "config": "^3.3.1",
revert

2020-08-03 15:30 UTC, asafMasa commented on src/store/reducers/dataReducer.js
> +        // const resource = {
remove remark

2020-08-04 07:10 UTC, merged